driver:
  name: ec2
  region: us-west-2
  instance_type: m4.large
  aws_ssh_key_id: test-kitchen
  subnet_id: subnet-74de082e
  iam_profile_name: s3-test-kitchen
  security_group_ids: ['sg-9abe55e5']
  associate_public_ip: true
  interface: dns
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: 100
        delete_on_termination: true
  tags:
    created-by: 'test-kitchen'

transport:
  ssh_key: /keys/test-kitchen.pem

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.3

platforms:
  - name: windows-2016
  - name: windows-2012r2
  - name: windows-2008r2
  - name: windows-81
  - name: windows-7

suites:
  - name: pro
    driver:
      tags:
        Name: 'pro'
    run_list:
      - recipe[download-setups-s3::pro]
      - recipe[arcgis-pro]
    attributes:
      arcgis:
        pro:
          version: '2.2'
          setup: 'C:\Users\Administrator\Documents\ArcGIS 2.2\Pro\ArcGISPro.msi'
          authorization_file: '/auth_files/Single Use/Pro_AdvancedSU.prvc'
