---
- name: "hardware : set up lm sensors (add '-e sensors_detect=1' to run this task"
  command: "sensors-detect --auto"
  when: sensors_detect is defined

- name: "hardware : copy smartd.conf"
  copy:
    src: smartd.conf
    dest: /etc/smartd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart smartd

- name: "hardware : enable and start smartd"
  service:
    name: smartd
    state: started
    enabled: true
  ignore_errors: true
