driver:
  name: ec2
  region: us-west-2
  instance_type: m4.large
  aws_ssh_key_id: test-kitchen
  subnet_id: subnet-74de082e
  iam_profile_name: s3-test-kitchen
  security_group_ids: ['sg-9abe55e5']
  associate_public_ip: true
  interface: dns
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: 100
        delete_on_termination: true
  tags:
    created-by: 'test-kitchen'

transport:
  ssh_key: /keys/test-kitchen.pem

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.3

platforms:
  - name: windows-2016
  - name: windows-2012r2
  - name: windows-2008r2
  - name: windows-81
  - name: windows-7
  - name: ubuntu-16.04
  - name: centos-7
  - name: centos-6

suites:
  - name: desktop
    driver:
      tags:
        Name: 'desktop'
    run_list:
      - recipe[download-setups-s3::desktop]
      - recipe[arcgis-desktop]
    attributes:
      arcgis:
        desktop:
          software_class: 'Viewer'
          seat_preference: 'Fixed'
          desktop_config: true
    excludes:
      - ubuntu-16.04
      - centos-7
      - centos-6

  - name: licensemanager
    driver:
      tags:
        Name: 'licensemanager'
    run_list:
      - recipe[download-setups-s3::licensemanager]
      - recipe[arcgis-desktop::licensemanager]
    attributes:
      arcgis:
        version: '10.7.1'
