---
driver:
  name: vagrant
  customize:
    memory: 6144
    cpuexecutioncap: 50

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.3

platforms:
  - name: windows-2016
  - name: windows-2012r2
  - name: windows-2008r2

suites:
  - name: iis
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 16080}]
        - ["forwarded_port", {guest: 443, host: 16443}]
    run_list:
      - recipe[esri-iis]
